### ISSUE TITLE
parse not exposed?

### ISSUE THREAD

**Issue by ghost** [elad/libphonenumber#2]
This is a wrapper around the Google libphonenumber project to expose as a Node module. But it doesn't appear to expose the parse() function. Any reason?

**Comment by elad** [comment]
This module was never planned as a full-fledged libphonenumber wrapper. I only used it for my purposes  because I couldn't find anything like it. :) You're welcome to submit a PR. If it gets merged, I'll add you as a contributor.

**Comment by ghost** [comment]
Okay. That makes sense.
