### ISSUE TITLE
libphonenumber outdated

### ISSUE THREAD

**Issue by jonathanve** [elad/libphonenumber#3]
The release of this package is a year old. New google libphonenumber changes have been included.

https://github.com/googlei18n/libphonenumber

**Comment by elad** [comment]
Do you want to submit a PR?

**Comment by jonathanve** [comment]
I would like to, but the fix is only to re-run make and commit the new generated node lib. No need for a PR since no new code is necessary.

**Comment by henrikra** [comment]
I did PR for this https://github.com/elad/libphonenumber/pull/4
